name: MDA-ExtendedFeatures1058
version: '${project.version}'
main: mino.dx.mdaextendedfeatures1058.MDAExtendedFeatures1058
depend: [PlaceholderAPI, BedWars1058]
softdepend: [DiscordSRV]
authors: [MinoMC_YTB]
description: Add some new features to BedWars1058
