name: MDA-ExtendedFeatures1058
version: '${project.version}'
main: mino.dx.mdaextendedfeatures1058.MDAExtendedFeatures1058
depend: [PlaceholderAPI, DiscordSRV]
softdepend: [BedWars1058]
authors: [MinoMC_YTB]
description: Add some new features to BedWars1058
